name: packages


on:
  repository_dispatch:
  push:
    branches: 
      - src
    paths:
      - '.github/workflows/packages.yml'
      - 'packages.seed'
      - '*.sh'
  pull_request:
    branches:
      - src
  schedule:
    - cron: '0 17 * * 1'

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai
          
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: src
          fetch-depth: 0
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 5

      - name: Save Private Key
        if: github.event_name == 'push'
        run: |
          echo 'untrusted comment: private key 1f0e4ac921671797' > private.key
          echo "${{ secrets.private_key }}" >> private.key

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          . init_env.sh
      
      - name: Pull Source
        run: |
          . pull_source.sh

       
      - name: Add Packages
        run: |
          . add_packages.sh

      - name: Update Feeds
        run: |
          cd src/openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Install UPX
        run: |
          mkdir -p src/openwrt/staging_dir/host/bin/
          ln -s /usr/bin/upx-ucl src/openwrt/staging_dir/host/bin/upx
  
      - name: Update Target.mk
        run: |
          cd src/openwrt/include
          sed -i 's/dnsmasq /dnsmasq-full default-settings luci /' target.mk

      - name: Build Config
        run: |
          cd src
          cat ../.config > ../rk3328.config
          cat ../packages.seed >> ../rk3328.config
          cat ../rk3328.config > ../.config
          cat ../.config

      - name: Add usign
        run: |
          mkdir -p src/openwrt/staging_dir/host/bin/
          sudo chmod a+x usign
          cp usign src/openwrt/staging_dir/host/bin/
          sudo mv usign /usr/bin/

      - name: Build openwrt
        env:
          IGNORE_ERRORS: 1
        run: |
          cd src/openwrt
          cp ../../.config .
          make
    
      - name: Collect Packages
        run: |
          cd src
          mkdir -p packagerepo/packages
          mv openwrt/bin/packages/aarch64_cortex-a53/*/*.ipk packagerepo/packages/
          mv openwrt/bin/targets/rockchip-rk3328/generic/packages/*.ipk packagerepo/packages/
          cat -s openwrt/bin/packages/aarch64_cortex-a53/*/Packages > packagerepo/packages/Packages
          cat -s openwrt/bin/targets/rockchip-rk3328/generic/packages/Packages >> packagerepo/packages/Packages
          cat -s openwrt/bin/packages/aarch64_cortex-a53/*/Packages.manifest > packagerepo/packages/Packages.manifest
          cat -s openwrt/bin/targets/rockchip-rk3328/generic/packages/Packages.manifest >> packagerepo/packages/Packages.manifest
          cd packagerepo/packages/
          gzip -k Packages
          ls *.ipk
      
      - name: Sign Packages
        if: github.event_name == 'push'
        run: |
          cd src
          cd packagerepo/packages
          usign -S -m Packages -s ../../../private.key -x Packages.sig

      - name: Push Changes
        if: github.event_name == 'push'
        run: |
          cd src/packagerepo
          mkdir keys
          cp ../../keys/* keys/
          cp ../../README.md ./
          cp ../../README.md ./packages/
          cp ../../CNAME ./
          git init
          git add .
          git commit -m "Depoly at $(date +%Y-%m-%d)"
          git push -f "https://${{ secrets.sec_token }}@github.com/ourfor/nanopi-r2s-opkg-feeds.git" master:master
